debug: false
server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: dba
    password: dba
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem