apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-people-manager
spec:
  selector:
    matchLabels:
      app: app-people-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: app-people-manager
    spec:
      containers:
      - name: app-people-manager
        image: peoplemanager:latest
        resources:
          limits:
            memory: 256Mi
            cpu: 1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080